global:
  scrape_interval: 15s # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889'] # Replace with your OpenTelemetry Collector address
